"""create_meal_feedbacks_table

Revision ID: 14c9fd785014
Revises: b7a6b22c618a
Create Date: 2026-06-16 12:01:14.356435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c9fd785014'
down_revision: Union[str, None] = 'b7a6b22c618a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_number', sa.Integer(), nullable=False),
    sa.Column('meal_name', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', 'meal_number', name='uq_user_date_meal_number')
    )
    op.create_index(op.f('ix_meal_feedbacks_date'), 'meal_feedbacks', ['date'], unique=False)
    op.create_index(op.f('ix_meal_feedbacks_id'), 'meal_feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_meal_feedbacks_user_id'), 'meal_feedbacks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_feedbacks_user_id'), table_name='meal_feedbacks')
    op.drop_index(op.f('ix_meal_feedbacks_id'), table_name='meal_feedbacks')
    op.drop_index(op.f('ix_meal_feedbacks_date'), table_name='meal_feedbacks')
    op.drop_table('meal_feedbacks')
    # ### end Alembic commands ###
