"""change_feedback_to_checkbox

Revision ID: 912353df28ef
Revises: 14c9fd785014
Create Date: 2026-06-17 10:17:49.669117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '912353df28ef'
down_revision: Union[str, None] = '14c9fd785014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_feedbacks', sa.Column('is_checked', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='체크된 피드백 항목 리스트'))
    op.drop_column('meal_feedbacks', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_feedbacks', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('meal_feedbacks', 'is_checked')
    # ### end Alembic commands ###
