"""add_recommended_daily_calories_to_persona

Revision ID: b7a6b22c618a
Revises: f1478b8dad5a
Create Date: 2026-06-15 15:12:16.689181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a6b22c618a'
down_revision: Union[str, None] = 'f1478b8dad5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_persona_settings', sa.Column('recommended_daily_calories', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_persona_settings', 'recommended_daily_calories')
    # ### end Alembic commands ###
