"""페르소나 테이블에 persona_id 컬럼 추가

Revision ID: d40935b1ab11
Revises: 912353df28ef
Create Date: 2026-06-18 15:49:58.451272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40935b1ab11'
down_revision: Union[str, None] = '912353df28ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_persona_settings', sa.Column('persona_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_persona_settings', 'persona_id')
    # ### end Alembic commands ###
