"""
프론트 이미지 매핑을 고려한 대표 페르소나 catalog이다.

기존 조합형 catalog는 persona_id가 과도하게 많아
프론트에서 이미지 매핑과 카드 UI를 안정적으로 관리하기 어려웠다.

따라서 실제 응답 후보는 아래 대표 페르소나 20개만 사용한다.
- 1인 가구 10개
- 다인 가구 10개

프론트는 persona_id를 기준으로 이미지를 매핑한다.
"""


PERSONA_CATALOG = [
    # 1인 가구 대표 페르소나 10개
    {
        "persona_id": "persona_single_budget_saver",
        "household_type": "1인 가구",
        "description": "가성비 절약형",
        "summary": "식비 부담을 줄이면서도 한 끼를 알차게 챙기고 싶은 1인 가구예요. 예산 안에서 실천 가능한 식단을 추천해드릴게요!",
        "target_purposes": ["식비 절약"],
        "target_budget_bands": ["very_low", "low"],
        "target_activity_levels": [1, 2],
        "target_meals_per_day": [1, 2, 3],
    },
    {
        "persona_id": "persona_single_diet_light",
        "household_type": "1인 가구",
        "description": "가벼운 관리형",
        "summary": "칼로리 부담을 줄이고 체중 관리를 꾸준히 이어가고 싶은 1인 가구예요. 가볍지만 포만감 있는 식단을 추천해드릴게요!",
        "target_purposes": ["다이어트"],
        "target_budget_bands": ["low", "medium", "high"],
        "target_activity_levels": [1, 2, 3],
        "target_meals_per_day": [2, 3],
    },
    {
        "persona_id": "persona_single_high_protein",
        "household_type": "1인 가구",
        "description": "단백질 충전형",
        "summary": "단백질을 충분히 챙기면서 건강한 식사 루틴을 만들고 싶은 1인 가구예요. 든든한 단백질 중심 식단을 추천해드릴게요!",
        "target_purposes": ["고단백"],
        "target_budget_bands": ["low", "medium", "high"],
        "target_activity_levels": [2, 3, 4],
        "target_meals_per_day": [2, 3, 4],
    },
    {
        "persona_id": "persona_single_easy_cooking",
        "household_type": "1인 가구",
        "description": "초간단 해결형",
        "summary": "복잡한 조리보다 쉽고 빠르게 챙겨 먹는 식단이 필요한 1인 가구예요. 조리 부담이 적은 메뉴 위주로 추천해드릴게요!",
        "target_purposes": ["간편식"],
        "target_budget_bands": ["very_low", "low", "medium"],
        "target_activity_levels": [1, 2, 3, 4],
        "target_meals_per_day": [1, 2, 3],
    },
    {
        "persona_id": "persona_single_balanced_routine",
        "household_type": "1인 가구",
        "description": "균형식단 루틴형",
        "summary": "탄수화물, 단백질, 지방을 균형 있게 챙기며 식사 루틴을 만들고 싶은 1인 가구예요. 무리 없이 지속 가능한 식단을 추천해드릴게요!",
        "target_purposes": ["영양 균형"],
        "target_budget_bands": ["low", "medium", "high"],
        "target_activity_levels": [1, 2, 3],
        "target_meals_per_day": [2, 3],
    },
    {
        "persona_id": "persona_single_taste_focused",
        "household_type": "1인 가구",
        "description": "입맛만족 추구형",
        "summary": "건강도 중요하지만 맛있게 먹는 즐거움도 놓치고 싶지 않은 1인 가구예요. 만족감 있는 메뉴를 중심으로 추천해드릴게요!",
        "target_purposes": ["맛 중심"],
        "target_budget_bands": ["medium", "high"],
        "target_activity_levels": [1, 2, 3, 4],
        "target_meals_per_day": [1, 2, 3],
    },
    {
        "persona_id": "persona_single_diet_protein",
        "household_type": "1인 가구",
        "description": "탄탄관리 단백형",
        "summary": "체중 관리와 단백질 섭취를 함께 챙기고 싶은 1인 가구예요. 가볍지만 단백질은 든든한 식단을 추천해드릴게요!",
        "target_purposes": ["다이어트", "고단백"],
        "target_budget_bands": ["low", "medium", "high"],
        "target_activity_levels": [2, 3, 4],
        "target_meals_per_day": [2, 3],
    },
    {
        "persona_id": "persona_single_budget_easy",
        "household_type": "1인 가구",
        "description": "알뜰간편 생존형",
        "summary": "식비를 아끼면서도 간단하게 끼니를 해결하고 싶은 1인 가구예요. 저렴하고 만들기 쉬운 식단을 추천해드릴게요!",
        "target_purposes": ["식비 절약", "간편식"],
        "target_budget_bands": ["very_low", "low"],
        "target_activity_levels": [1, 2, 3],
        "target_meals_per_day": [1, 2, 3],
    },
    {
        "persona_id": "persona_single_diet_easy",
        "household_type": "1인 가구",
        "description": "실속관리 루틴형",
        "summary": "건강 관리와 간편함을 함께 챙기고 싶은 1인 가구예요. 부담 없이 실천 가능한 관리 식단을 추천해드릴게요!",
        "target_purposes": ["다이어트", "간편식"],
        "target_budget_bands": ["very_low", "low", "medium"],
        "target_activity_levels": [1, 2, 3],
        "target_meals_per_day": [2, 3],
    },
    {
        "persona_id": "persona_single_variety_seeker",
        "household_type": "1인 가구",
        "description": "다채로운 루틴형",
        "summary": "매번 비슷한 메뉴보다 다양한 식단으로 꾸준히 챙겨 먹고 싶은 1인 가구예요. 반복을 줄인 식단을 추천해드릴게요!",
        "target_purposes": ["영양 균형", "맛 중심"],
        "target_budget_bands": ["medium", "high"],
        "target_activity_levels": [1, 2, 3, 4],
        "target_meals_per_day": [2, 3, 4],
    },

    # 다인 가구 대표 페르소나 10개
    {
        "persona_id": "persona_multi_budget_planner",
        "household_type": "다인 가구",
        "description": "가족예산 수비대형",
        "summary": "가족 식비를 안정적으로 관리하면서도 충분한 식사를 챙기고 싶은 가구예요. 예산 안에서 효율적인 식단을 추천해드릴게요!",
        "target_purposes": ["식비 절약"],
        "target_budget_bands": ["very_low", "low"],
        "target_activity_levels": [1, 2, 3],
        "target_meals_per_day": [2, 3],
    },
    {
        "persona_id": "persona_multi_balanced_family",
        "household_type": "다인 가구",
        "description": "가족균형 식단형",
        "summary": "가족 모두의 영양 균형을 챙기고 싶은 가구예요. 누구나 무난하게 먹을 수 있는 균형 잡힌 식단을 추천해드릴게요!",
        "target_purposes": ["영양 균형"],
        "target_budget_bands": ["low", "medium", "high"],
        "target_activity_levels": [1, 2, 3],
        "target_meals_per_day": [2, 3],
    },
    {
        "persona_id": "persona_multi_easy_shared_meal",
        "household_type": "다인 가구",
        "description": "가족식단 해결사형",
        "summary": "여러 명이 함께 먹을 식사를 쉽고 빠르게 준비하고 싶은 가구예요. 조리 부담이 적은 가족 식단을 추천해드릴게요!",
        "target_purposes": ["간편식"],
        "target_budget_bands": ["low", "medium"],
        "target_activity_levels": [1, 2, 3, 4],
        "target_meals_per_day": [2, 3],
    },
    {
        "persona_id": "persona_multi_high_protein_family",
        "household_type": "다인 가구",
        "description": "가족단백 충전형",
        "summary": "가족의 단백질 섭취와 든든한 식사를 함께 챙기고 싶은 가구예요. 단백질 중심의 만족도 높은 식단을 추천해드릴게요!",
        "target_purposes": ["고단백"],
        "target_budget_bands": ["medium", "high"],
        "target_activity_levels": [2, 3, 4],
        "target_meals_per_day": [2, 3, 4],
    },
    {
        "persona_id": "persona_multi_diet_support",
        "household_type": "다인 가구",
        "description": "가족건강 관리형",
        "summary": "가족 식단 안에서도 건강 관리와 체중 관리를 함께 고려하고 싶은 가구예요. 부담 적은 건강식 위주로 추천해드릴게요!",
        "target_purposes": ["다이어트"],
        "target_budget_bands": ["low", "medium", "high"],
        "target_activity_levels": [1, 2, 3],
        "target_meals_per_day": [2, 3],
    },
    {
        "persona_id": "persona_multi_taste_balance",
        "household_type": "다인 가구",
        "description": "가족입맛 조율형",
        "summary": "가족 구성원의 입맛을 맞추면서도 식단 만족도를 높이고 싶은 가구예요. 맛과 균형을 함께 고려해 추천해드릴게요!",
        "target_purposes": ["맛 중심"],
        "target_budget_bands": ["medium", "high"],
        "target_activity_levels": [1, 2, 3, 4],
        "target_meals_per_day": [2, 3],
    },
    {
        "persona_id": "persona_multi_budget_balance",
        "household_type": "다인 가구",
        "description": "가족알뜰 균형러형",
        "summary": "식비는 아끼면서도 가족 영양 균형은 놓치고 싶지 않은 가구예요. 알뜰하고 균형 잡힌 식단을 추천해드릴게요!",
        "target_purposes": ["식비 절약", "영양 균형"],
        "target_budget_bands": ["very_low", "low", "medium"],
        "target_activity_levels": [1, 2, 3],
        "target_meals_per_day": [2, 3],
    },
    {
        "persona_id": "persona_multi_budget_easy",
        "household_type": "다인 가구",
        "description": "가족알뜰 간편형",
        "summary": "가족 식비를 줄이면서도 준비는 간편하게 하고 싶은 가구예요. 부담 적은 장보기와 간편한 식단을 추천해드릴게요!",
        "target_purposes": ["식비 절약", "간편식"],
        "target_budget_bands": ["very_low", "low"],
        "target_activity_levels": [1, 2, 3],
        "target_meals_per_day": [2, 3],
    },
    {
        "persona_id": "persona_multi_health_routine",
        "household_type": "다인 가구",
        "description": "가족건강 루틴러형",
        "summary": "가족이 함께 건강한 식사 습관을 만들고 싶은 가구예요. 관리와 균형을 함께 고려한 식단을 추천해드릴게요!",
        "target_purposes": ["다이어트", "영양 균형"],
        "target_budget_bands": ["low", "medium", "high"],
        "target_activity_levels": [1, 2, 3],
        "target_meals_per_day": [2, 3],
    },
    {
        "persona_id": "persona_multi_variety_table",
        "household_type": "다인 가구",
        "description": "다채로운 가족식탁형",
        "summary": "가족 식탁에 다양한 메뉴를 올리고 싶은 가구예요. 반복을 줄이고 만족도를 높인 식단을 추천해드릴게요!",
        "target_purposes": ["영양 균형", "맛 중심"],
        "target_budget_bands": ["medium", "high"],
        "target_activity_levels": [1, 2, 3, 4],
        "target_meals_per_day": [2, 3, 4],
    },
]
